/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registrationform;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc
 */
public class registration extends javax.swing.JFrame {
    
    int counter =0;
    DefaultTableModel model  ;
    
    
    
    /**
     * Creates new form registration
     */
    public registration() {
        initComponents();
        model = (DefaultTableModel) usertable.getModel();
        success.setVisible(false);
         
        
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        dobyear = new javax.swing.JComboBox<>();
        dobdays = new javax.swing.JComboBox<>();
        dobmonths = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        accept = new javax.swing.JCheckBox();
        clear = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        success = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        usertable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        display = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 51, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registration Form");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 940, 70));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 51, 0), 3), "Regeister", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 1, 18), new java.awt.Color(102, 51, 0))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel2.setText("Address:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel3.setText("Name:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel4.setText("Phone:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel5.setText("Email:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel6.setText("Gender:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel7.setText("DOB:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));
        jPanel3.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 230, 40));
        jPanel3.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 230, 40));
        jPanel3.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 230, 40));

        female.setText("Female");
        jPanel3.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        male.setText("Male");
        jPanel3.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        dobyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1900", "1901", "1902", "1903", "1904", "1905", "1906", "1907", "1908", "1909", "1910", "1911", "1912", "1913", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", " " }));
        jPanel3.add(dobyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 80, -1));

        dobdays.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " " }));
        jPanel3.add(dobdays, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 50, -1));

        dobmonths.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", " " }));
        jPanel3.add(dobmonths, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 50, -1));

        address.setColumns(20);
        address.setRows(5);
        jScrollPane1.setViewportView(address);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 220, -1));

        accept.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        accept.setText("Accept terms & Conditions");
        jPanel3.add(accept, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, -1, -1));

        clear.setText("Clear");
        jPanel3.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 100, -1));

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel3.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, -1, -1));

        success.setText("Registred Succesfully....");
        jPanel3.add(success, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 400, 560));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 51, 0), 3), "Display Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 1, 18))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Phone", "Email", "Gender", "DOB", "Address"
            }
        ));
        usertable.setGridColor(new java.awt.Color(102, 51, 0));
        jScrollPane3.setViewportView(usertable);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 490, 290));

        display.setColumns(20);
        display.setRows(5);
        jScrollPane2.setViewportView(display);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 490, 200));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 530, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        //validation 
        if (name.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter your name",
                    "Empty Name", JOptionPane.WARNING_MESSAGE);
        } else if (phone.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter your phone",
                    "Empty Phone", JOptionPane.WARNING_MESSAGE);
        } else if (email.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter your email",
                    "Empty Email", JOptionPane.WARNING_MESSAGE);
        } else if(male.isSelected()==false && female.isSelected()==false){
             JOptionPane.showMessageDialog(null, "Please select your gender",
                    "Empty Gender", JOptionPane.WARNING_MESSAGE);
       
        } else if(dobdays.getSelectedIndex() == 0 || dobmonths.getSelectedIndex()==0 || dobyear.getSelectedIndex()==0){
             JOptionPane.showMessageDialog(null, "Please select your DOB",
                    "Empty DOB", JOptionPane.WARNING_MESSAGE);
       
        }
        
        else if(address.getText().isEmpty()){
             JOptionPane.showMessageDialog(null, "Please enter your address",
                    "Empty Address", JOptionPane.WARNING_MESSAGE);
       
        }
         
        else if(accept.isSelected()==false){
             JOptionPane.showMessageDialog(null, "Please accept the terms and conditions",
                    "Accept Terms", JOptionPane.WARNING_MESSAGE);
        }
        //displaying the info
        else{
           // getting data from form
        String nameValue = name.getText();
                String phoneValue = phone.getText();
                String emailValue = email.getText();
                String genderValue = "";
                if(male.isSelected()){
                    genderValue = "Male";
                }else{
                    genderValue = "Female";
                }
                String dobValue= dobdays.getSelectedItem().toString()+"/"+
                                 dobmonths.getSelectedItem().toString()+"/"+
                                 dobyear.getSelectedItem().toString();
                String addressValue = address.getText();
                
                // adding data to the text area.
                display.append("User: "+ ++counter + "\n");
                display.append("Name: " + nameValue + "\n");
                display.append("Phone: " + phoneValue + "\n");
                display.append("Email: " + emailValue + "\n");
                display .append("Gender: " + genderValue + "\n");
                display .append("DOB: " + dobValue + "\n");
                display .append("Address: " + addressValue + "\n\n");
            
                //creating the row with an array
                Object[] row = {nameValue, phoneValue, emailValue, genderValue, dobValue,
                                addressValue};

                //adding the row to the table model
                model.addRow(row);
                
        }
        
        // clearing the form
        name.setText("");
        phone.setText("");
        email.setText("");
        if (male.isSelected() == true  || female.isSelected() == true) {
            male.setSelected(false); 
            female.setSelected(false);
        }
        dobdays.setSelectedIndex(0);
        dobmonths.setSelectedIndex(0);
        dobyear.setSelectedIndex(0);
        address.setText("");
        accept.setSelected(false);
        
        Timer timer = new Timer(5000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                 if (success.isEnabled() == false) {
                    success.setVisible(true);
                }

            }
        });
    
        timer.start();
        
         
        
    }//GEN-LAST:event_submitActionPerformed

    
    
    
    /**
     * @param args the command line arguments      
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox accept;
    private javax.swing.JTextArea address;
    private javax.swing.JButton clear;
    private javax.swing.JTextArea display;
    private javax.swing.JComboBox<String> dobdays;
    private javax.swing.JComboBox<String> dobmonths;
    private javax.swing.JComboBox<String> dobyear;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phone;
    private javax.swing.JButton submit;
    private javax.swing.JLabel success;
    private javax.swing.JTable usertable;
    // End of variables declaration//GEN-END:variables
}
